### ISSUE TITLE
while & if-else support?

### ISSUE THREAD

**Issue by pinojojo** [hmenke/boost_matheval#11]
will this library implement something like a multi-line calculator, perhaps with a loop or an if-else function?

**Comment by hmenke** [comment]
You can easily emulate if-else conditions using arithmetic, e.g. `(i == 1) * (true expr) + (i != 1) * (false expr)`.

Support for a ternary operator `(i == 1 ? a + b : a - b)` is not unreasonable and I might give it a shot if I find the time.

Control structures like `while`, `for`, etc. will not be supported. If you need any of these you are much better off embedding a fully-fledged scripting language (e.g. Lua) into your program anyway.

**Comment by pinojojo** [comment]
thank you for your advice. 

I've googled for a quite time for parsing a script-like grammar using a cpp library. the most possible way i can find is using boost-spirit. I‘ve also checked the antlr, but people using spirit says parsing in spirit is faster than antlr, and I also prefer no-syntax files approach.

**Comment by pinojojo** [comment]
thank you for your advice.

I've googled for a quite time for parsing a script-like grammar using a cpp library. the most possible way i can find is using boost-spirit. I‘ve also checked the antlr, but people using spirit say parsing in spirit is faster than antlr, and I also prefer no-syntax files approach. 

There are too few examples of using this library for complex syntax parsing on the internet, the official example on boost document page is too simple and brief. And I think your repo is a great reference. thank you.

**Comment by hmenke** [comment]
If you are only looking for examples, have a look at the mini_c part of the [Qi compiler tutorial](https://github.com/boostorg/spirit/tree/develop/example/qi/compiler_tutorial) in the Spirit repo, although even that doesn't have support for loops. If you are looking for something that is directly usable and C++-header-only, have a look at https://github.com/ArashPartow/exprtk or https://github.com/ChaiScript/ChaiScript

**Comment by hmenke** [comment]
`ifthenelse` was added in https://github.com/hmenke/boost_matheval/commit/8e5128af677e1de2be80234c30220198abf25914
