### ISSUE TITLE
Should parsing be case sensitive?

### ISSUE THREAD

**Issue by hmenke** [hmenke/boost_matheval#3]
As of now unary functions, binary functions, and constants are parsed case insenstive, i.e. `Cos(pI)` parses well.  This is due to the `no_case` declarations in the `primary` rule.

https://github.com/hmenke/boost_matheval/blob/6824ed51d5b477f2a8a2c182dc4a28a6e2498c54/include/matheval.hpp#L422-L427

Is this behaviour desirable or do we want to be case sensitive?

**Comment by rempferg** [comment]
I prefer case sensitive behaviour.

**Comment by hmenke** [comment]
Fixed in 3a5ed267a1c8c2ab588d04d6221b762786bb24d5.
